### ISSUE TITLE
Feature: getHandle()

### ISSUE THREAD

**Issue by pit001** [nkolban/esp32-snippets#101]
For diagnostic a ~getHandle(uuid) function would be nice. 

It's not necessary that the API also is handle ready instead of UUID. 
Peter

**Comment by nkolban** [comment]
Howdy Peter,
Can you expand with more commentary on this one.  In which class would you like a getHandle()?  Could the "toString()" methods of the existing classes be used for the diagnostics desired?

**Comment by pit001** [comment]
Hi, I simply add 

uint16_t BLERemoteCharacteristic::getHandle() {
return getHandle();
}

in 

BLERemoteCharacteristic.cpp /.h
for Characteristic handles... (most interesting)

**Comment by nkolban** [comment]
Part of my thinking ... and I could be very wrong here ... was trying to hide "handles" from the end user (the BLE programmer).  If one is writing a BLE app using these classes, I wanted one to think exclusively in terms of the class rather than the "handle".  The handle obviously exists ... it is part of the BLE world ... but I was trying to hide its existence from consumers.  Can you help me understand why we would want to expose a handle to a BLE C++ API programmer?

**Comment by pit001** [comment]
As I allready try to show: It's informative only, but's interesting during development, because it's the only thing visable in the communication (i.e. with wireshark) and often also present in the web and in some documentation.

**Comment by nkolban** [comment]
It looks like the toString() method of BLERemoteCharacteristic produces a string that could be logged for debugging which contains the handle, uuid and characteristic properties.  Would that not be sufficient for debugging purposes during development?

**Comment by pit001** [comment]
both values are int16, as a String ist a bit bothersome to convert it to dec and hex.. but OK

**Comment by nkolban** [comment]
You have happily convinced me that exposing the handles is *not a bad thing*.  As such BLERemoteService, BLERemoteCharacteristic and BLERemoteDescriptor now expose a method called "getHandle()".  Let me know if there are additional changes requested for this issue.

**Comment by nkolban** [comment]
Assuming resolved.  Don't hesitate to re-open as needed.
