### ISSUE TITLE
BLE library in arduino-ide

### ISSUE THREAD

**Issue by chegewara** [nkolban/esp32-snippets#340]
Just a thought, but in esp-idf we can turn on/off part of bluedroid stack and BLE library from menuconfig by switching on/off GATTS, GATTC and SMP. Arduino users cant do that. Is there requirements to add some kind flag which will do the same if arduino user dont need to use one of those class?

**Comment by nkolban** [comment]
I think the core question will be for us to answer/contemplate "What does it *mean* to turn off GATTS, GATTC and SMP?".  Let us assume that they are compiled to their "on" state.  That means that the function is present and available for us to use.  This is goodness.   So what is the downside?  My guess will be resource utilization.  By having these options compiled in, one would imagine that they will contribute to flash program size and/or RAM utilization.  If we don't need those options, then compiling them out would save resources.  However, we have to balance that against the "complexity" and "cost" of giving the users more options.

Let's review.  Today a programmer can write ESP-IDF applications using native ESP-IDF and see nothing of Arduino.  In that mode, this isn't an issue.  A programmer can also write Arduino programs using the ESP-IDF by attaching the Arduino package as a component to an ESP-IDF application.  This requires the programmer to have BOTH Arduino and ESP-IDF skills.  However, they are building the ESP-IDF from source and hence can switch on/off the flags using "make menuconfig".

The last option is the one that we are concerned with here ... in that option they are using the Arduino IDE and building ESP32 binaries.  In that option, they have no obvious ability to re-compile the ESP-IDF with changed flags and are "locked in" to what mr @me-no-dev  currently has selected.

My opinion on this is that maintaining status quo (i.e. leaving GATTS, GATTC and SMP) enabled are acceptable.  My thinking on this works as follows:

1. A real Arduino Uno has 2KBytes of RAM and 32KBytes of flash.  The ability to do WiFi or BLE is a dream that would never happen on a real Arduino.  In addition, folks run out real Arduino resources all the time and eventually move to a more "professional" environment (some opinion here).  I don't want to worry too much about making the Arduino-libs as optimal as they can be at the cost of making them more complex for the ordinary/average user.

2. It isn't a given to me that a user/programmer can't build the ESP-IDF that can be used with Arduino-IDE today.  If I understand correctly, mr @me-no-dev pre-builds the ESP-IDF and supplies compiled libs because that dramatically reduces compile time during an "ordinary" Arduino app build.  What we need to learn/understand is if there is a recipe where a user could download ESP-IDF, build the libraries and then replace the Arduino-lib distributed libraries with the versions that they themselves just built.   If this is a possibility, then it should also be possible to either write up the recipe in detail or provide a script to make it bullet proof.  If that were the case, then the problem would again appear to be solved.
