### ISSUE TITLE
90k memory gone before initialized ble

### ISSUE THREAD

**Issue by VircomSheep** [nkolban/esp32-snippets#655]
Hello,

I have memory problems in my program with the ble library, so I created a little test program to output the free heap on different points:

```
void setup() {
  Serial.begin(115200);  
  Serial.println("Free Heap 1");
  Serial.println(esp_get_free_heap_size());      
  
  BLEDevice::init("Test");
  auto server = BLEDevice::createServer();

  auto service = server -> createService("a5fcfeea-f201-43fe-ae67-082b254578e2");

  service -> addCharacteristic(new BLECharacteristic("8c552abf-f432-41d2-b709-4c13d2aea8e0"));

  Serial.println("Free Heap 2");
  Serial.println(esp_get_free_heap_size());

  service -> start();
  server -> startAdvertising();
}
```

The difference between "Free Heap 1" and "Free Heap 2" is ~70k, which is normal as i read at other posts. 
On "Free Heap 1" it outputs ~170k, but when I remove the Ble stuff it's ~260, and this is BEFORE the Ble sever and stuff gets instantiated and initialized. 
Where is that ram gone? I need every kb in my project..
Thanks in advance,

**Comment by chegewara** [comment]
Hi,
even before you initialize BLEDevice esp-ble library that is linked to your code needs to reserve heap. Like you mentioned it is ~70kB or it was. It is possible that esp-ble library is evaluating and now it is taking even more ram. I can only guessing because there is no official info about that.
